### ISSUE TITLE
fetch q

### ISSUE THREAD

**Issue by km001** [km001/kdbtest#2]
db: test
q: 不可
uti: smallBookTest.xml@67734

理論上應有hits但沒有，"不"和"可"分開單獨fetch時有hits。此現象似乎沒有發生在英文字上。

D:\km001\ksana2015\kdbtest>node fetch
structure of return object
[ 'uti', 'text', 'hits', 'vhits', 'vpos', 'vpos_end' ]
text: text of the page
hits: hits in this page in relative offset
vpos: virtual position of this page in whole kdb
{ uti: 'smallBookTest.xml@67734',
  text: '\n    Eliot Siegel\n    这是一个不可或缺的成为专业时尚摄影师的指南，从组织一次时尚拍摄到向潜在客户展示你的作品 ，这个关于时尚摄影的实用基础课程提供了有关原则、实践和技术的关键建议。这本书不仅仅是介绍摄影的技术方面，而且将会帮助读者发展他们自己的独特艺术风格。所有学摄影的学生以及任何对杂志或促销品设计感兴趣的读者都会发现这本书是一个宝贵的参考工具。\n    An indispensable guide to becoming a professional fashion photographer, from organizing a fashion shoot to presenting your portfolio to a potential client.This practical foundation course in fashion photography offers key advice on the principles, practice and techniques of the subject. Dealing with far more than just the technical aspects of photography, this book will help the reader to evolve a unique artistic style of their own. All photography students, as well as anyone interested in magaz\n    Thames &amp; Hudson Ltd\n    The Fashion Photography Course: First Principles to Successful Shoot - the Essential Guide\n    时尚摄影课程:成功拍摄的首要原则——重要指南\n \n  ',
  hits: [],
  vhits: [],
  vpos: 345,
  vpos_end: 633 }

**Comment by yapcheahshen** [comment]
update to ksana-search@1.6.2  commit https://github.com/ksanaforge/ksana-search/commit/26fe378a68d3258f49f9f918c28dedc8a69e26ac
